@startuml

component backend{
    component restserver {
        package todo.restserver
    }
    component core{
        package todo.core
        package todo.json
    }
    component restApi{
        package todo.restApi

    }
    todo.restApi ..> todo.core
    todo.restApi ..> todo.json


    component springboot {
    }

    todo.restserver ..> todo.restApi
    todo.restserver ..> todo.core

    restserver ..> springboot
}

component frontend {
    package src
    package public

}

src ..> restserver



@enduml